[package]
name = "iiko-api"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
indexmap.workspace = true
sha1 = "0.11.0"
quick-xml = { version = "0.42.0", features = ["serialize"] }
ureq = { version = "3.4.2", features = ["json", "platform-verifier"] }

[dev-dependencies]
httpmock = "0.8.3"
