name: Rust

on:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - name: install dependencies
              run: sudo apt-get update && sudo apt-get install libgtk-4-dev
            - name: clippy
              run: cargo clippy --workspace --all-targets -- -D warnings
            - name: test
              run: cargo test --workspace

    build-macos:
        name: build for macOS
        runs-on: macos-latest
        needs: test

        steps:
            - uses: actions/checkout@v7
            - name: install dependencies
              run: brew install gtk4 dylibbundler
            - name: build
              run: cargo build --release
            - name: package
              run: make
            - uses: actions/upload-artifact@v7
              with:
                  name: iiko-office-macos-arm64
                  path: iikoOffice.dmg
    build-linux:
        name: build for Linux
        runs-on: ubuntu-latest
        needs: test

        steps:
            - uses: actions/checkout@v7
            - name: install dependencies
              run: sudo apt-get update && sudo apt-get install libgtk-4-dev pacman-package-manager
            - name: build
              run: cargo build --release
            - name: deb package
              run: make deb
            - name: arch package
              run: make arch
            - uses: actions/upload-artifact@v7
              with:
                  name: iiko-office-linux-deb-amd64
                  path: iiko-office.deb
            - uses: actions/upload-artifact@v7
              with:
                  name: iiko-office-linux-arch-amd64
                  path: iiko-office-*.pkg.tar.zst
