name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    name: build for macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: brew install gtk4
    - name: build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: iiko-office-macos-arm64
        path: target/release/iiko-office
  build-linux:
    name: build for Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update && sudo apt install -y libgtk-4-dev
    - name: build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: iiko-office-linux-amd64
        path: target/release/iiko-office
